//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the attitude_controller package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __attitude_controller__ATTITUDE_CONTROLLER_PARAMSCONFIG_H__
#define __attitude_controller__ATTITUDE_CONTROLLER_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace attitude_controller
{
  class attitude_controller_paramsConfigStatics;
  
  class attitude_controller_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(attitude_controller_paramsConfig &config, const attitude_controller_paramsConfig &max, const attitude_controller_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const attitude_controller_paramsConfig &config1, const attitude_controller_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, attitude_controller_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const attitude_controller_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, attitude_controller_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const attitude_controller_paramsConfig &config) const = 0;
      virtual void getValue(const attitude_controller_paramsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T attitude_controller_paramsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (attitude_controller_paramsConfig::* field);

      virtual void clamp(attitude_controller_paramsConfig &config, const attitude_controller_paramsConfig &max, const attitude_controller_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const attitude_controller_paramsConfig &config1, const attitude_controller_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, attitude_controller_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const attitude_controller_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, attitude_controller_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const attitude_controller_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const attitude_controller_paramsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, attitude_controller_paramsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, attitude_controller_paramsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<attitude_controller_paramsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(attitude_controller_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("use_dr_set_point"==(*_i)->name){use_dr_set_point = boost::any_cast<bool>(val);}
        if("roll_set_point"==(*_i)->name){roll_set_point = boost::any_cast<double>(val);}
        if("pitch_set_point"==(*_i)->name){pitch_set_point = boost::any_cast<double>(val);}
        if("yaw_set_point"==(*_i)->name){yaw_set_point = boost::any_cast<double>(val);}
        if("roll_kp"==(*_i)->name){roll_kp = boost::any_cast<double>(val);}
        if("roll_ki"==(*_i)->name){roll_ki = boost::any_cast<double>(val);}
        if("roll_ki_max"==(*_i)->name){roll_ki_max = boost::any_cast<double>(val);}
        if("roll_kd"==(*_i)->name){roll_kd = boost::any_cast<double>(val);}
        if("pitch_kp"==(*_i)->name){pitch_kp = boost::any_cast<double>(val);}
        if("pitch_ki"==(*_i)->name){pitch_ki = boost::any_cast<double>(val);}
        if("pitch_ki_max"==(*_i)->name){pitch_ki_max = boost::any_cast<double>(val);}
        if("pitch_kd"==(*_i)->name){pitch_kd = boost::any_cast<double>(val);}
        if("yaw_kp"==(*_i)->name){yaw_kp = boost::any_cast<double>(val);}
        if("yaw_ki"==(*_i)->name){yaw_ki = boost::any_cast<double>(val);}
        if("yaw_ki_max"==(*_i)->name){yaw_ki_max = boost::any_cast<double>(val);}
        if("yaw_kd"==(*_i)->name){yaw_kd = boost::any_cast<double>(val);}
      }
    }

    bool use_dr_set_point;
double roll_set_point;
double pitch_set_point;
double yaw_set_point;
double roll_kp;
double roll_ki;
double roll_ki_max;
double roll_kd;
double pitch_kp;
double pitch_ki;
double pitch_ki_max;
double pitch_kd;
double yaw_kp;
double yaw_ki;
double yaw_ki_max;
double yaw_kd;

    bool state;
    std::string name;

    
}groups;



//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_dr_set_point;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_set_point;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_set_point;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_set_point;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_kp;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_ki;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_ki_max;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_kd;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_kp;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_ki;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_ki_max;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_kd;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_kp;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_ki;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_ki_max;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_kd;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("attitude_controller_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const attitude_controller_paramsConfig &__max__ = __getMax__();
      const attitude_controller_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const attitude_controller_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const attitude_controller_paramsConfig &__getDefault__();
    static const attitude_controller_paramsConfig &__getMax__();
    static const attitude_controller_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const attitude_controller_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void attitude_controller_paramsConfig::ParamDescription<std::string>::clamp(attitude_controller_paramsConfig &config, const attitude_controller_paramsConfig &max, const attitude_controller_paramsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class attitude_controller_paramsConfigStatics
  {
    friend class attitude_controller_paramsConfig;
    
    attitude_controller_paramsConfigStatics()
    {
attitude_controller_paramsConfig::GroupDescription<attitude_controller_paramsConfig::DEFAULT, attitude_controller_paramsConfig> Default("Default", "", 0, 0, true, &attitude_controller_paramsConfig::groups);
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_dr_set_point = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_dr_set_point = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_dr_set_point = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<bool>("use_dr_set_point", "bool", 0, "Use dynamic reconfig setpoint", "", &attitude_controller_paramsConfig::use_dr_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<bool>("use_dr_set_point", "bool", 0, "Use dynamic reconfig setpoint", "", &attitude_controller_paramsConfig::use_dr_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_set_point = -std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_set_point = std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_set_point = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_set_point", "double", 0, "Set Point: X", "", &attitude_controller_paramsConfig::roll_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_set_point", "double", 0, "Set Point: X", "", &attitude_controller_paramsConfig::roll_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_set_point = -std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_set_point = std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_set_point = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_set_point", "double", 0, "Set Point: Y", "", &attitude_controller_paramsConfig::pitch_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_set_point", "double", 0, "Set Point: Y", "", &attitude_controller_paramsConfig::pitch_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_set_point = -std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_set_point = std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_set_point = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_set_point", "double", 0, "Set Point: Z", "", &attitude_controller_paramsConfig::yaw_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_set_point", "double", 0, "Set Point: Z", "", &attitude_controller_paramsConfig::yaw_set_point)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_kp = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_kp = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_kp = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_kp", "double", 0, "Roll P", "", &attitude_controller_paramsConfig::roll_kp)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_kp", "double", 0, "Roll P", "", &attitude_controller_paramsConfig::roll_kp)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_ki = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_ki = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_ki = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_ki", "double", 0, "Roll I", "", &attitude_controller_paramsConfig::roll_ki)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_ki", "double", 0, "Roll I", "", &attitude_controller_paramsConfig::roll_ki)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_ki_max = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_ki_max = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_ki_max = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_ki_max", "double", 0, "Roll I Max", "", &attitude_controller_paramsConfig::roll_ki_max)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_ki_max", "double", 0, "Roll I Max", "", &attitude_controller_paramsConfig::roll_ki_max)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_kd = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_kd = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_kd = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_kd", "double", 0, "Roll D", "", &attitude_controller_paramsConfig::roll_kd)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("roll_kd", "double", 0, "Roll D", "", &attitude_controller_paramsConfig::roll_kd)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_kp = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_kp = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_kp = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_kp", "double", 0, "Pitch P", "", &attitude_controller_paramsConfig::pitch_kp)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_kp", "double", 0, "Pitch P", "", &attitude_controller_paramsConfig::pitch_kp)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_ki = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_ki = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_ki = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_ki", "double", 0, "Pitch I", "", &attitude_controller_paramsConfig::pitch_ki)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_ki", "double", 0, "Pitch I", "", &attitude_controller_paramsConfig::pitch_ki)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_ki_max = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_ki_max = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_ki_max = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_ki_max", "double", 0, "Pitch I Max", "", &attitude_controller_paramsConfig::pitch_ki_max)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_ki_max", "double", 0, "Pitch I Max", "", &attitude_controller_paramsConfig::pitch_ki_max)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_kd = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_kd = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_kd = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_kd", "double", 0, "Pitch D", "", &attitude_controller_paramsConfig::pitch_kd)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("pitch_kd", "double", 0, "Pitch D", "", &attitude_controller_paramsConfig::pitch_kd)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_kp = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_kp = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_kp = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_kp", "double", 0, "Yaw P", "", &attitude_controller_paramsConfig::yaw_kp)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_kp", "double", 0, "Yaw P", "", &attitude_controller_paramsConfig::yaw_kp)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_ki = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_ki = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_ki = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_ki", "double", 0, "Yaw I", "", &attitude_controller_paramsConfig::yaw_ki)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_ki", "double", 0, "Yaw I", "", &attitude_controller_paramsConfig::yaw_ki)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_ki_max = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_ki_max = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_ki_max = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_ki_max", "double", 0, "Yaw I Max", "", &attitude_controller_paramsConfig::yaw_ki_max)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_ki_max", "double", 0, "Yaw I Max", "", &attitude_controller_paramsConfig::yaw_ki_max)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_kd = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_kd = 100.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_kd = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_kd", "double", 0, "Yaw D", "", &attitude_controller_paramsConfig::yaw_kd)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr(new attitude_controller_paramsConfig::ParamDescription<double>("yaw_kd", "double", 0, "Yaw D", "", &attitude_controller_paramsConfig::yaw_kd)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(attitude_controller_paramsConfig::AbstractGroupDescriptionConstPtr(new attitude_controller_paramsConfig::GroupDescription<attitude_controller_paramsConfig::DEFAULT, attitude_controller_paramsConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<attitude_controller_paramsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<attitude_controller_paramsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    attitude_controller_paramsConfig __max__;
    attitude_controller_paramsConfig __min__;
    attitude_controller_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const attitude_controller_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static attitude_controller_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &attitude_controller_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const attitude_controller_paramsConfig &attitude_controller_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const attitude_controller_paramsConfig &attitude_controller_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const attitude_controller_paramsConfig &attitude_controller_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<attitude_controller_paramsConfig::AbstractParamDescriptionConstPtr> &attitude_controller_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<attitude_controller_paramsConfig::AbstractGroupDescriptionConstPtr> &attitude_controller_paramsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const attitude_controller_paramsConfigStatics *attitude_controller_paramsConfig::__get_statics__()
  {
    const static attitude_controller_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = attitude_controller_paramsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __ATTITUDE_CONTROLLER_PARAMSRECONFIGURATOR_H__
