// Generated by gencpp from file quad_controller/GetPath.msg
// DO NOT EDIT!


#ifndef QUAD_CONTROLLER_MESSAGE_GETPATH_H
#define QUAD_CONTROLLER_MESSAGE_GETPATH_H

#include <ros/service_traits.h>


#include <quad_controller/GetPathRequest.h>
#include <quad_controller/GetPathResponse.h>


namespace quad_controller
{

struct GetPath
{

typedef GetPathRequest Request;
typedef GetPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPath
} // namespace quad_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quad_controller::GetPath > {
  static const char* value()
  {
    return "f65fd00b2e3f675220a83a94307b7f12";
  }

  static const char* value(const ::quad_controller::GetPath&) { return value(); }
};

template<>
struct DataType< ::quad_controller::GetPath > {
  static const char* value()
  {
    return "quad_controller/GetPath";
  }

  static const char* value(const ::quad_controller::GetPath&) { return value(); }
};


// service_traits::MD5Sum< ::quad_controller::GetPathRequest> should match 
// service_traits::MD5Sum< ::quad_controller::GetPath > 
template<>
struct MD5Sum< ::quad_controller::GetPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::GetPath >::value();
  }
  static const char* value(const ::quad_controller::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::GetPathRequest> should match 
// service_traits::DataType< ::quad_controller::GetPath > 
template<>
struct DataType< ::quad_controller::GetPathRequest>
{
  static const char* value()
  {
    return DataType< ::quad_controller::GetPath >::value();
  }
  static const char* value(const ::quad_controller::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quad_controller::GetPathResponse> should match 
// service_traits::MD5Sum< ::quad_controller::GetPath > 
template<>
struct MD5Sum< ::quad_controller::GetPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::GetPath >::value();
  }
  static const char* value(const ::quad_controller::GetPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::GetPathResponse> should match 
// service_traits::DataType< ::quad_controller::GetPath > 
template<>
struct DataType< ::quad_controller::GetPathResponse>
{
  static const char* value()
  {
    return DataType< ::quad_controller::GetPath >::value();
  }
  static const char* value(const ::quad_controller::GetPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUAD_CONTROLLER_MESSAGE_GETPATH_H
