// Generated by gencpp from file quad_controller/SetFloat.msg
// DO NOT EDIT!


#ifndef QUAD_CONTROLLER_MESSAGE_SETFLOAT_H
#define QUAD_CONTROLLER_MESSAGE_SETFLOAT_H

#include <ros/service_traits.h>


#include <quad_controller/SetFloatRequest.h>
#include <quad_controller/SetFloatResponse.h>


namespace quad_controller
{

struct SetFloat
{

typedef SetFloatRequest Request;
typedef SetFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat
} // namespace quad_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quad_controller::SetFloat > {
  static const char* value()
  {
    return "33440febf8aeff64c8c846264db06c0f";
  }

  static const char* value(const ::quad_controller::SetFloat&) { return value(); }
};

template<>
struct DataType< ::quad_controller::SetFloat > {
  static const char* value()
  {
    return "quad_controller/SetFloat";
  }

  static const char* value(const ::quad_controller::SetFloat&) { return value(); }
};


// service_traits::MD5Sum< ::quad_controller::SetFloatRequest> should match 
// service_traits::MD5Sum< ::quad_controller::SetFloat > 
template<>
struct MD5Sum< ::quad_controller::SetFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::SetFloat >::value();
  }
  static const char* value(const ::quad_controller::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::SetFloatRequest> should match 
// service_traits::DataType< ::quad_controller::SetFloat > 
template<>
struct DataType< ::quad_controller::SetFloatRequest>
{
  static const char* value()
  {
    return DataType< ::quad_controller::SetFloat >::value();
  }
  static const char* value(const ::quad_controller::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quad_controller::SetFloatResponse> should match 
// service_traits::MD5Sum< ::quad_controller::SetFloat > 
template<>
struct MD5Sum< ::quad_controller::SetFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::SetFloat >::value();
  }
  static const char* value(const ::quad_controller::SetFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::SetFloatResponse> should match 
// service_traits::DataType< ::quad_controller::SetFloat > 
template<>
struct DataType< ::quad_controller::SetFloatResponse>
{
  static const char* value()
  {
    return DataType< ::quad_controller::SetFloat >::value();
  }
  static const char* value(const ::quad_controller::SetFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUAD_CONTROLLER_MESSAGE_SETFLOAT_H
