// Generated by gencpp from file quad_controller/SetInt.msg
// DO NOT EDIT!


#ifndef QUAD_CONTROLLER_MESSAGE_SETINT_H
#define QUAD_CONTROLLER_MESSAGE_SETINT_H

#include <ros/service_traits.h>


#include <quad_controller/SetIntRequest.h>
#include <quad_controller/SetIntResponse.h>


namespace quad_controller
{

struct SetInt
{

typedef SetIntRequest Request;
typedef SetIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt
} // namespace quad_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quad_controller::SetInt > {
  static const char* value()
  {
    return "c6cf86a08ff7309c5d9f200d8652f57f";
  }

  static const char* value(const ::quad_controller::SetInt&) { return value(); }
};

template<>
struct DataType< ::quad_controller::SetInt > {
  static const char* value()
  {
    return "quad_controller/SetInt";
  }

  static const char* value(const ::quad_controller::SetInt&) { return value(); }
};


// service_traits::MD5Sum< ::quad_controller::SetIntRequest> should match 
// service_traits::MD5Sum< ::quad_controller::SetInt > 
template<>
struct MD5Sum< ::quad_controller::SetIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::SetInt >::value();
  }
  static const char* value(const ::quad_controller::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::SetIntRequest> should match 
// service_traits::DataType< ::quad_controller::SetInt > 
template<>
struct DataType< ::quad_controller::SetIntRequest>
{
  static const char* value()
  {
    return DataType< ::quad_controller::SetInt >::value();
  }
  static const char* value(const ::quad_controller::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quad_controller::SetIntResponse> should match 
// service_traits::MD5Sum< ::quad_controller::SetInt > 
template<>
struct MD5Sum< ::quad_controller::SetIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::SetInt >::value();
  }
  static const char* value(const ::quad_controller::SetIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::SetIntResponse> should match 
// service_traits::DataType< ::quad_controller::SetInt > 
template<>
struct DataType< ::quad_controller::SetIntResponse>
{
  static const char* value()
  {
    return DataType< ::quad_controller::SetInt >::value();
  }
  static const char* value(const ::quad_controller::SetIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUAD_CONTROLLER_MESSAGE_SETINT_H
