// Generated by gencpp from file quad_controller/SetPath.msg
// DO NOT EDIT!


#ifndef QUAD_CONTROLLER_MESSAGE_SETPATH_H
#define QUAD_CONTROLLER_MESSAGE_SETPATH_H

#include <ros/service_traits.h>


#include <quad_controller/SetPathRequest.h>
#include <quad_controller/SetPathResponse.h>


namespace quad_controller
{

struct SetPath
{

typedef SetPathRequest Request;
typedef SetPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPath
} // namespace quad_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quad_controller::SetPath > {
  static const char* value()
  {
    return "1b4da6832b76c5bb61a99129a3adb7b2";
  }

  static const char* value(const ::quad_controller::SetPath&) { return value(); }
};

template<>
struct DataType< ::quad_controller::SetPath > {
  static const char* value()
  {
    return "quad_controller/SetPath";
  }

  static const char* value(const ::quad_controller::SetPath&) { return value(); }
};


// service_traits::MD5Sum< ::quad_controller::SetPathRequest> should match 
// service_traits::MD5Sum< ::quad_controller::SetPath > 
template<>
struct MD5Sum< ::quad_controller::SetPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::SetPath >::value();
  }
  static const char* value(const ::quad_controller::SetPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::SetPathRequest> should match 
// service_traits::DataType< ::quad_controller::SetPath > 
template<>
struct DataType< ::quad_controller::SetPathRequest>
{
  static const char* value()
  {
    return DataType< ::quad_controller::SetPath >::value();
  }
  static const char* value(const ::quad_controller::SetPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quad_controller::SetPathResponse> should match 
// service_traits::MD5Sum< ::quad_controller::SetPath > 
template<>
struct MD5Sum< ::quad_controller::SetPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quad_controller::SetPath >::value();
  }
  static const char* value(const ::quad_controller::SetPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_controller::SetPathResponse> should match 
// service_traits::DataType< ::quad_controller::SetPath > 
template<>
struct DataType< ::quad_controller::SetPathResponse>
{
  static const char* value()
  {
    return DataType< ::quad_controller::SetPath >::value();
  }
  static const char* value(const ::quad_controller::SetPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUAD_CONTROLLER_MESSAGE_SETPATH_H
